 p_id |                                                                                                                                              content                                                                                                                                               | article |         added_the          
------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------
    1 | Isn't it what you  want?                                                                                                                                                                                                                                                                           |       3 | 2018-09-09 12:06:59.092563
    2 | Run out the tunnel? Knowing you about to have some impact in the game                                                                                                                                                                                                                              |       3 | 2018-09-09 12:07:27.064628
    3 | Have the crowd cheer your name? Your family, friends, partner screaming like they just met their idol.                                                                                                                                                                                             |       3 | 2018-09-09 12:07:52.689173
    4 | Bring value to your team? Be a  reference for your teammates?. A trusted leader by your coaches?                                                                                                                                                                                                   |       3 | 2018-09-09 12:08:32.732253
    5 | On top of that lead them to the championship?                                                                                                                                                                                                                                                      |       3 | 2018-09-09 12:08:54.246963
    6 |  If you answered yes to these.You are at the right place.                                                                                                                                                                                                                                          |       3 | 2018-09-09 12:09:17.496683
    7 |  We will not cover the physicall aspect of your game. There are many online ressources available to you. We recommend Bodybuilding.com. They have an unlimited amount of tutorials, that can help you get the shape you want. If it is not enough. Google the subject, Watch  some Youtube videos. |       3 | 2018-09-09 12:09:52.889499
    8 | What we will do for you is cover the mental apsect.                                                                                                                                                                                                                                                |       3 | 2018-09-09 12:10:24.39825
    9 | We will give you tools to become a mentally tough athlete.                                                                                                                                                                                                                                         |       3 | 2018-09-09 12:10:54.952766
   10 | Why mental toughness?                                                                                                                                                                                                                                                                              |       3 | 2018-09-09 12:11:13.761024
   11 | Mental toughness allows you to become a Michael Jordan.                                                                                                                                                                                                                                            |       3 | 2018-09-09 12:11:33.027564
   12 | Mental toughness allows you to become a Muhammad Ali.                                                                                                                                                                                                                                              |       3 | 2018-09-09 12:12:26.862161
   13 | Mental toughness allows you to become a Ray Lewis.                                                                                                                                                                                                                                                 |       3 | 2018-09-09 12:12:57.556254
   14 | When you just made a mistake on a play. Mental toughness allows you to make it right the very next play.                                                                                                                                                                                           |       3 | 2018-09-09 12:13:20.087064
   15 | When your teammates are out partying. Mental toughness brings you to the gym. Motivate you to review your mistakes from the last game.                                                                                                                                                             |       3 | 2018-09-09 12:13:55.694929
   16 | When you are on the verge of losing. Mental toughness makes you lead the troops, carry them on your back and bring them to victory.                                                                                                                                                                |       3 | 2018-09-09 12:14:38.103149
   17 | You don't believe me?                                                                                                                                                                                                                                                                              |       3 | 2018-09-09 12:14:57.317661
   18 | Here is what Jay Williams had to say about Kobe Bryant.                                                                                                                                                                                                                                            |       3 | 2018-09-09 12:15:24.305715
   19 | Kobe bryant has always been known for his mental toughness. That's what made him great, that's what made him a legend.                                                                                                                                                                             |       3 | 2018-09-09 12:15:43.256681
   20 | For those who do not know who Jay williams is. He was the second 2002 NBA draft pick for the Chicago Bulls.                                                                                                                                                                                        |       3 | 2018-09-09 12:16:06.556248
   21 | Williams had a game against the lakers at the Staples Center. And his motto was to outwork any other basketball player.                                                                                                                                                                            |       3 | 2018-09-09 12:16:39.479478
   22 | Williams had a game against the lakers at the Staples Center. And his motto was to outwork any other basketball player.                                                                                                                                                                            |       3 | 2018-09-09 12:22:06.547974
   23 | "I was like i am going to get there at 3:00 o'clock. I wanted to make sure i madee 400 made shots before the game."                                                                                                                                                                                |       3 | 2018-09-09 12:23:09.370576
   24 | "Who do I see? I see Kobe Bryant already working out.                                                                                                                                                                                                                                              |       3 | 2018-09-09 12:23:56.257857
   25 |  And once i stepped my foot accross that line. I started working out. I worked out for a good hour, hour and a half."                                                                                                                                                                              |       3 | 2018-09-09 12:24:44.38524
   26 | "When I was done. I sat down. And of course I still heard the ball bouncing. I look down, I'm like this guy is still woking out?"                                                                                                                                                                  |       3 | 2018-09-09 12:25:28.865589
   27 | "It looked like he was in dead sweat when I got there, and he is still going. It is not like his moves are nonchalant or lazy."                                                                                                                                                                    |       3 | 2018-09-09 12:26:28.26263
   28 | " I sat out there and watched another 25 minutes, and he was done. "                                                                                                                                                                                                                               |       3 | 2018-09-09 12:27:55.27532
   29 | " That game he dropped 40 points on us. "                                                                                                                                                                                                                                                          |       3 | 2018-09-09 12:28:44.682322
   30 | " After the game I am like Hey Kobe, why were you in the gym for so long? "                                                                                                                                                                                                                        |       3 | 2018-09-09 12:29:12.569767
   31 |  To which Kobe answered: " Because I saw you come in, and I wanted you to know that it does not matter how hard you work, that I am willing to work harder than you. You inspire me to be better. "                                                                                                |       3 | 2018-09-09 12:30:14.144582
   32 |  Williams said to the interviewer :" It was the first time i started to see this level of competitiveness where I said, I need to start doing more. "                                                                                                                                              |       3 | 2018-09-09 12:31:09.27061
   33 | How do you feel? Did this story about Kobe Bryant motivate you?                                                                                                                                                                                                                                    |       3 | 2018-09-09 12:31:43.407493
   34 | Does it seem too crazy for you? Don't worry! You can build yourself to become the next Kobe Bryant. Even better the firs You!                                                                                                                                                                      |       3 | 2018-09-09 12:32:16.879014
(34 rows)

